series: Basic OpenGL with GLFW
title: Cel Shading
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: A demo of a simple cel shading technique.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Object Loading